// Generated by CoffeeScript 1.7.1
(function() {
  require('initialize');

  document.write('<div id="ember-testing"></div>');

  App.rootElement = '#ember-testing';

  App.setupForTesting();

  App.injectTestHelpers();

  QUnit.testStart(function() {
    return App.reset();
  });

}).call(this);
